FROM ubuntu:18.04

# Make sure the package repository is up to date.
RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy git && \
# Install a basic SSH server
    apt-get install -qy openssh-server && \
    sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd && \
    mkdir -p /var/run/sshd && \
# Cleanup old packages
    apt-get -qy autoremove && \
# Add user developer to the image
    adduser --quiet developer && \
# Set password for the developer user
    echo "developer:developer" | chpasswd && \
    mkdir /home/developer/.m2

RUN apt-get update \
  && apt-get install -qy --force-yes python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip 

#ADD settings.xml /home/developer/.m2/
# Copy authorized keys
COPY .ssh /home/developer/.ssh
# Copy bash script to get git changes
COPY bash_git_clone.sh /home/developer/bash_git_clone.sh


# Standard SSH port
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]